<?php

/** 订单相关  **/
define('BILL_PRE','es');//订单前标
define('BILL_MIDDLE_C','c');//订单中标 集装箱
define('BILL_MIDDLE_B','b');//订单中标 散货船
define('BILL_OUT','out');//出口
define('BILL_IN','in');//进口


/** 存图文件夹相关  **/

define('BILL_UPLOAD_SAVE','/uploads/order/');//订单相关存储位置




/** 网站相关信息定义  **/

define('WEBSET_NAME','伊斯货运ERP管理系统');//订单相关存储位置
define('WEBSET_TITLE','集装箱出口流程 出货列表 系统');//订单相关存储位置

/** here if the end of this page*/